### ISSUE TITLE
Task definition with many different refs, secrets

### ISSUE THREAD

**Issue by blognat** [aws-actions/amazon-ecs-deploy-task-definition#13]
Hey.

I have a problem with description of the task. I don't understand how it should work, example:

I deploy CloudFormation Stack where we dynamic create names, using refs, secret strings:
(example from our cloudformation template)
```
TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Join
        - '-'
        - - !Ref environment
          - !FindInMap [Cluster, Service, Name]
          - TaskDefinition
```
For env point
```
- Name: SOME_NAME
Value: !Join
    - ''
    - - '{{resolve:secretsmanager:'
    - !Ref some_ref
    - '-some_name:SecretString:****}}'
```

And now we want to use github actions for:
1. Build the project (ok)
2. Push into ECR (ok)
3. Create new Task Definition with a new link of image from ECR (no)
4. Deploy to ECR (clearly that no)

Point 3 from list: we should create the `task-definition.json` file as required by `aws-actions/amazon-ecs-render-task-definition@v1`. But how should we resolve problem with description of envs, names of cluster, container which are created dynamically using refs and secrets to generate right strings?

It is clear that a simple duplication of CloudFormation Template in JSON will not yield

I would be glad if you indicated the right direction to solve this problem.
