### ISSUE TITLE
Expected params.forceNewDeployment to be a boolean

### ISSUE THREAD

**Issue by neerajsu** [aws-actions/amazon-ecs-deploy-task-definition#133]
tried using force-new-deployment to true.

And I get error : Error: Expected params.forceNewDeployment to be a boolean

What am I missing? Here's the snippet from my yml

```yml

- name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: some-service
          cluster: Some-cluster
          force-new-deployment: true
          wait-for-service-stability: true
```
