### ISSUE TITLE
Question: Multiple container definitions

### ISSUE THREAD

**Issue by sarodspirit** [aws-actions/amazon-ecs-deploy-task-definition#170]
What would be the way to write yaml for multiple container definitions in one single taskdef ? 
Taskdef.json
```javascript
{
  ...,
  containerDefinitions:[
    {
      image: 'image1'
    },
    {
      image: 'image2'
    }
  ]
}
```
```yaml
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: Taskdef.json
        container-name: my-container
        image: ${{ steps.build-image.outputs.image }}
```
