### ISSUE TITLE
Lamba Deployment Addition?

### ISSUE THREAD

**Issue by firstdivision** [aws-actions/amazon-ecs-deploy-task-definition#18]
I wasn't sure where to ask a question about the future of https://github.com/aws-actions in general.  Are there plans to add more actions to this suite?  [This CLI project](https://github.com/actions/aws) appears to be deprecated, so I am wondering if there will be AWS-official actions added to do things like deploy Lambda zip packages? Or another project to support CLI in general?

**Comment by clareliguori** [comment]
Hi, I suggest opening issues in the repos for the individual tools you mentioned to request GitHub Actions for those tools and gather +1s.  For example, in https://github.com/aws/aws-cli and https://github.com/awslabs/aws-sam-cli.  The AWS GitHub Actions are maintained by the individual service teams (for now, only the ECS service team has published actions).  So it's up to the Lambda team or AWS CLI team to prioritize publishing a GitHub Action against the other customer requests they have, so capturing +1s in a GitHub issue in their repo is helpful for that prioritization.

FYI, the AWS CLI is pre-installed in the GitHub-hosted environments: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts.  So for example, `runs-on: ubuntu-latest` will have AWS CLI version 1.16.299, and you can do the following:
```
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  - name: Use the AWS CLI
    run: |
      aws sts get-caller-identity
```
