### ISSUE TITLE
Any way to use task definition defined by service?

### ISSUE THREAD

**Issue by mheki** [aws-actions/amazon-ecs-deploy-task-definition#26]
Hi,
is there any way to skip creating task definition and use the one which is configured on the service level in AWS?

So far we used codeship with such configuration:

```
service: awsdeployment
command: aws ecs update-service --cluster my_cluster --service my_service --force-new-deployment
```

Thanks!

**Comment by mheki** [comment]
Actually I've found out `aws-cli` is available on github hosted machine so above command can be run directly.

**Comment by DIMPLY** [comment]
@mheki Where is the `aws-cli`?

**Comment by mheki** [comment]
@DIMPLY you can call it directly from workflow yaml file like that:
```
      - name: Deploy
        run: |
          aws ecs update-service --cluster example-dev --service example-web --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
```
