### ISSUE TITLE
Multiple CodeDeploys/Environments

### ISSUE THREAD

**Issue by adamhathcock** [aws-actions/amazon-ecs-deploy-task-definition#36]
This action is what I've been looking for!

However, it is possible this can be extended to work with a strategy for deploying multiple apps from a singular deployment repo and/or work with the same app (same image) that would deploy to multiple environments in AWS.

If this is no applicable, is there any guidance for the intended usage beyond a simple and singular deployment?

Thanks!

**Comment by clareliguori** [comment]
You can run the action multiple times with different inputs in your workflow file. Does that solve what you're trying to do?

```
    - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: my-test-service
        cluster: my-cluster
        wait-for-service-stability: true
    - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: my-prod-service
        cluster: my-cluster
        wait-for-service-stability: true
```
