### ISSUE TITLE
Job Failing with "Error: Unsupported deployment controller: ECS"

### ISSUE THREAD

**Issue by muya** [aws-actions/amazon-ecs-deploy-task-definition#384]
### Description

Recent jobs (as of around 28 Sep 03:30 UTC) have started failing with the error:

```
Error: Unsupported deployment controller: ECS
```

The specific job in the workflow that's failing is:

```yaml
      - name: Deploy Amazon ECS backend service task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          wait-for-minutes: 8 
```

Previous jobs in the workflow (incl. Checkout, ECR Login, Building & pushing image to ECR, Filling in Task definition) are all passing.

Any idea what the problem could be?

#### Additional Notes:
- Deployment directly from the Amazon ECS Web UI is working 
- There have been no changes to workflows since ~25th Sep, and there were successful deployments then.
- Attached is a redacted version of the task definition 

![screenshot-20220928-042359](https://user-images.githubusercontent.com/1861055/192687438-36daf929-703d-4e8f-b9d5-0ba672582e09.png)
