### ISSUE TITLE
Action not updating ECS service with the last task definition revision

### ISSUE THREAD

**Issue by anzileiro** [aws-actions/amazon-ecs-deploy-task-definition#417]
Hi I'm using this Github Action to deploy our company services on AWS ECS although we just see that this action isn't updating our ECS Services with the last Task Definition.

Below is the currently revision running on this service which is: `8`.
![Screenshot 2022-11-15 at 14 28 47](https://user-images.githubusercontent.com/3415671/201986589-79d883ef-5f50-4582-9ff4-f2633158f308.png)

Below is the action that was triggered by the merge in our `sandbox` branch, which has to update our sandbox environment with the last code merged.
![Screenshot 2022-11-15 at 14 31 02](https://user-images.githubusercontent.com/3415671/201986977-9558ffb9-fe21-4be6-92fe-0a31066d91c0.png)

Surprisingly looking to our service the service task definition still with the same revision: `8`, but on the task definition pages we could see that Github Action updated the new task definition revision which is: `10`.
  
![Screenshot 2022-11-15 at 14 34 37](https://user-images.githubusercontent.com/3415671/201987714-5510d2ca-66ad-43e8-ba26-c57c9a967fd3.png)

In resume, It looks like that this Github Action isn't unable to update the ECS Service with the last updated Task Definition Revision.

Could you please help us?

Regards,

Anderson Anzileiro

**Comment by DLoBoston** [comment]
I am having this exact issue as well.

**Comment by DLoBoston** [comment]
Upon further review, it was working as intended. The problem was my service was configured to have a minimumHealthyPercent of 100%. With only 1 instance running, it would not allow the task to be killed. As soon as I set the minimumHealthyPercent to 0% everything worked as expected. If you run multiple instances it doesn't need to be 0%, just a percentage that will allow a task to be stopped.

**Comment by ken-tan3** [comment]
I face the same issue, though the service value following was empty in my case. 

```yml
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
```
