### ISSUE TITLE
Way to update image tag in latest task definition without needing to store whole task definition

### ISSUE THREAD

**Issue by alex-benoit** [aws-actions/amazon-ecs-deploy-task-definition#45]
I would be great if we could simply indicate the new container tag that we want to use without having to store the task definition json.

```
    - name: Build and Push Image to Amazon ECR
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_REPOSITORY_URL }}
    - name: Update Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: my-service
        cluster: my-cluster
        container-image-name-updates: container=my-conatiner,tag=${{ github.sha }}
        wait-for-service-stability: true
```

Maybe this can be an option in the `render-task-definition` action instead to pull the latest from aws.

What do you think? It avoids having to add a rogue `task_definition.json` in the repository that needs to be maintained alongside the running task definition.
