### ISSUE TITLE
Download task-definition file

### ISSUE THREAD

**Issue by hamzaNb98** [aws-actions/amazon-ecs-deploy-task-definition#474]
How to use  task-definition file after download it.

**Comment by shardulvsinghh** [comment]
@hamzaNb98 You need to pass the downloaded task-definition as the value for the `task-definition` property in the action:
```
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.10
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
```

Where `task-def` is the id of the step where you download and output the task-definition.json
