### ISSUE TITLE
Create a new task revision with deploying the service 

### ISSUE THREAD

**Issue by suraj-sundariya** [aws-actions/amazon-ecs-deploy-task-definition#521]
Hi Team,

I just want to create a new task revision without deploying any service.

It is an ECS task without service which will be running as a separate task. 

```
- name: Create housekeeping task
        id: task-def-housekeeping
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-def-housekeeping.json
          container-name: recluster-user-housekeeping
          image: ${{ steps.build-image.outputs.image }}
```

The above code does not create new task revision.

**Comment by rafaelbernard** [comment]
I think AWS hasn't created that action yet. Maybe you will find https://github.com/marketplace/actions/ecs-deploy-task-definition-to-scheduled-task-action-for-github-actions useful for now.

**Comment by notAmine** [comment]
The service input is optional (also cluster) I got this working by not specifying them hope this helps.

**Comment by bpo-ddaniel27** [comment]
> The service input is optional (also cluster) I got this working by not specifying them hope this helps.

This works for me, this is how my step looks
```yml
- name: Deploy Amazon ECS task definition
  uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: ${{ steps.task-def.outputs.task-definition }}
```
