### ISSUE TITLE
Is it possible to register a task definition without deploying the service?

### ISSUE THREAD

**Issue by geovanygameros** [aws-actions/amazon-ecs-deploy-task-definition#533]
I would like to have more control over deployments to production environments and just use GitHub actions to push a new image to ECR and register a new task definition using that image.

I think an option just to register the task definition could be useful in case we want to have it ready on ECS but not deploy it right away.

A param like `only-register` could be very handy in this situation.

```yml
- name: Deploy to Amazon ECS
  uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: task-definition.json
    service: my-service
    cluster: my-cluster
    only-register: true
```

**Comment by geovanygameros** [comment]
After digging into the [actions.yml](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/61cb3a17e95278f1b0a7310ba58c9a440a9e59bd/action.yml#L11C4-L11C135) file I found that if the `service` param is not provided, the action will only register the task definition.

I'm closing this since the functionality is already available, this could be included in the README though. 😄

**Comment by vineetmadan** [comment]
Did this work for you though?

```
- name: Register ECS task definition
  uses: aws-actions/amazon-ecs-deploy-task-definition@v2
  with:
    task-definition: example.json
```
    
While using the above-mentioned code I'm getting the error:

```
Error: Failed to register task definition in ECS: Family can not be blank.
Error: Family can not be blank.
```
