### ISSUE TITLE
"arn:aws:ecs:ap-northeast-1:***:service/*******task is MISSING" when deploy dotnet8  to aws ecs

### ISSUE THREAD

**Issue by YQinglin** [aws-actions/amazon-ecs-deploy-task-definition#544]
![image](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/assets/52813408/f6932130-3e0f-43b0-a8a0-931348d64eb4)
i use github action to deploy dotnet8  to aws ecs,  but meet some errors, and the step's codes as follows:
```
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
```
i think the arn maybe is error, it's should be `arn:aws:ecs:ap-northeast-1:***:task-definition...` but i can not find any place to modify
