### ISSUE TITLE
Issue with Standalone ECS Task Timeout in GitHub Actions

### ISSUE THREAD

**Issue by fsz-codeshop** [aws-actions/amazon-ecs-deploy-task-definition#608]
**Describe the bug**
I have a database migration script that runs as part of a standalone ECS task. While using aws-actions/amazon-ecs-deploy-task-definition@v2, the task is getting deployed successfully and completes with exit code 0. However, the GitHub Action remains stuck in the "waiting task to stop" state until it times out, even though the task shows as "STOPPED" on the AWS console.
```
Waiting for tasks to stop. Will wait for 5 minutes
Error: {"state":"TIMEOUT","reason":"Waiter has timed out"}
```
![image](https://github.com/user-attachments/assets/9d530729-b765-443e-bfad-f6f87f94d956)
![image](https://github.com/user-attachments/assets/24e5df5d-fe57-4e18-97f1-d50a44f4f9a3)

**Expected Behavior**
The GitHub Action should detect that the ECS task has completed successfully and proceed without timing out.

**Workflow Configuration**
```yaml
- name: "[STG] Deploy Amazon ECS migrations job task definition"
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.migrations_task_def_stg.outputs.task-definition }}
          cluster: ${{ vars.ECS_CLUSTER }}
          run-task: true
          wait-for-task-stopped: true
          run-task-subnets: ${{ vars.STG_ECS_JOB_SUBNETS }}
          run-task-security-groups: ${{ vars.STG_ECS_JOB_SEC_GROUP }}
          wait-for-minutes: 5
```
