### ISSUE TITLE
Network Configuration is not valid for the given networkMode of this task definition.

### ISSUE THREAD

**Issue by nburt** [aws-actions/amazon-ecs-deploy-task-definition#616]
I have a migration task which runs successfully from the command line with the following script:

`aws ecs run-task --cluster my-cluster --task-definition my-task-definition --launch-type EC2 --region us-east-2`

When running the github action, the action exits with "Network Configuration is not valid for the given networkMode of this task definition."

I'm running the task in the default "bridge" networkMode so I don't believe a network configuration needs to be specified to run the task.

**Comment by amazreech** [comment]
Hi @nburt, I think you are correct that you do not need to specify a network configuration when running in any other networkmode other than `awsvpc`.

Are you providing anything related to `Network Configuration` (`run-task-subnets`, `run-task-security-groups` or `run-task-assign-public-IP`) as an input to the GitHub Action workflow? 
Looking at the deploy repository code, these fields seem to be used in determining if a `network configuration` has been specified.

**Comment by nburt** [comment]
@amazreech oops sorry forgot to put my action code in. I wasn't specifying any of those
```
      - name: Run migrations
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-migrate.outputs.task-definition }}
          service: migrate
          cluster: ${{env.ECS_CLUSTER}}
          wait-for-service-stability: true
          run-task: true
          run-task-launch-type: EC2
          wait-for-task-stopped: true
```

**Comment by nburt** [comment]
@amazreech I think the issue is the networkConfiguration defaults to {} for bridge mode. I wrote a quick script which seems to work for me:

```
import {ECS} from "@aws-sdk/client-ecs"

const cluster = "dtc-cluster-arm";
const taskDefinition = "dtc-migrate";
const launchType = "EC2"
const region = "us-east-2";

const ecs = new ECS({
    region: region,
    credentials: {
        accessKeyId: "my key",
        secretAccessKey: "my secret"
    }
});

await ecs.runTask({
    startedBy: "nate local test",
    cluster: cluster,
    taskDefinition: taskDefinition,
    overrides: {
        containerOverrides: []
    },
    launchType: launchType,
    networkConfiguration: null
});
```

When I set networkConfiguration to `{}`, I received `InvalidParameterException: AwsVpcConfig cannot be null.`

**Comment by nburt** [comment]
I did a little more debugging and the specific error I encountered in the action is related to this line:
```
const assignPublicIP = core.getInput('run-task-assign-public-IP', { required: false }) || 'DISABLED';
```

By defaulting to "DISABLED", assignPublicIP gets set on awsvpcConfiguration. When I run the same code above with that in place:
```
await ecs.runTask({
    startedBy: "nate local test",
    cluster: cluster,
    taskDefinition: taskDefinition,
    overrides: {
        containerOverrides: []
    },
    launchType: launchType,
    networkConfiguration: {
        awsvpcConfiguration: {
            assignPublicIp: "DISABLED"
        }
    }
});
```

I do receive "InvalidParameterException: Network Configuration is not valid for the given networkMode of this task definition."

I haven't used networkConfiguration before so I don't know all the reasons behind the defaults but would it be possible to assign a default value to assignPublicIp when securityGroupIds or subnetIds are set? And then to update `Object.keys(awsvpcConfiguration).length === 0 ? {} : { awsvpcConfiguration: awsvpcConfiguration }` to `Object.keys(awsvpcConfiguration).length === 0 ? null : { awsvpcConfiguration: awsvpcConfiguration }` (defaulting to null)?

I'm happy to submit a PR if you can provide some clarification on what the default behavior should be!

**Comment by amazreech** [comment]
@nburt Thank you for detailed analysis on this!

`assignPublicIp` was set to default to `DISABLED` because the  runTask api documentation mentions the same. But given the parent property within which `assignPublicIp` lives (networkConfiguration) is NOT a required value, I believe it is reasonable to set `assignPublicIp ` only if `subnets` or `security groups` are provided. 

__RunTask API link:__
* https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-networkConfiguration

I will mark this issue as a bug, please feel free to submit a PR to fix this as you proposed.

**Comment by kg-aws** [comment]
Hi @nburt - Thank you for the contribution! The PR was successfully merged yesterday.
It would be a great help if you could confirm that the bug is fixed in the master branch with your use case and we should be good to close this issue.

**Comment by nburt** [comment]
@kg-aws Yes thanks for checking in, I'll close. It's working for our use case of running migrations with a one-off task! Here's what we're using:
```
      - name: Run migrations
        uses: aws-actions/amazon-ecs-deploy-task-definition@0a1e24711a61a2279b2bf40c6877fdbfd117997e
        with:
          task-definition: our definition
          cluster: our cluster
          wait-for-service-stability: true
          run-task: true
          run-task-launch-type: EC2
          wait-for-task-stopped: true
```
