### ISSUE TITLE
Failed to register task definition in ECS: Family can not be blank

### ISSUE THREAD

**Issue by vineetmadan** [aws-actions/amazon-ecs-deploy-task-definition#630]
I'm trying just to register a new task definition using this action. While looking at the [actions.yml](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/v2/action.yml), I can see that "If no service is given, the action will not deploy the task, but only register the task definition".

```
- name: Register ECS task definition
  uses: aws-actions/amazon-ecs-deploy-task-definition@v2
  with:
    task-definition: example.json
```
        
While using the above-mentioned code I'm getting the error:

```
Error: Failed to register task definition in ECS: Family can not be blank.
Error: Family can not be blank.
```

even though there is no such supported input.
