### ISSUE TITLE
Error since yesterday as - Unexpected key 'enableFaultInjection' found in params

### ISSUE THREAD

**Issue by rithik-choudhary** [aws-actions/amazon-ecs-deploy-task-definition#705]
Hello,

we are running the workflow file with same configuration since 1 year and suddenly from yesterday we are facing this issue
error
`Error: Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params
Error: Unexpected key 'enableFaultInjection' found in params`

this the line of code in workflow file
 ```
     - name: Fill in the new image ID in the Amazon ECS task definition
        id: service-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1  # Updated to v1
        with:
          task-definition: ./app-task-definition-fixed.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
```
          

Need help to resolve this issue quickly

**Comment by landon-medme** [comment]
> Hey @rithik-choudhary I was able to solve this by bumping the version to v2. Hope that helps!

Upgrading to v2 fixed the issue for me :+1:

**Comment by thanshaw02** [comment]
> Hey @rithik-choudhary I was able to solve this by bumping the version to v2. Hope that helps!

This also worked for me, thank you!

**Comment by omkhegde** [comment]
Hello. As other users have pointed out, please use v2 version of the action to fix this issue. Closing this issue, but please feel free to comment if there are follow-up questions.

**Comment by jo-mpac** [comment]
May I ask what was the reason that caused this issue? There are no changes in either `v1` or `v2` branches recently... Was it something on the AWS API side? Thank you and Happy New Year :)

**Comment by thanshaw02** [comment]
Updating the version to `v2` also did the trick for me, thank you!

**Comment by luizhlelis** [comment]
upgrading to `v2` fixed the issue for me as well

**Comment by omkhegde** [comment]
Hi all, thank you for reporting this issue. We have identified an issue in one of ECS' backend APIs that introduced a backward incompatible change, causing user workflows to encounter `Error: Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params Error: Unexpected key 'enableFaultInjection' found in params`  error. We are actively working on a fix for the issue, and will update this issue once it's resolved. Thank you.

**Comment by cavelasquez17** [comment]
I switched to v2, and now I'm getting the error when deploying to prod: `{"state":"TIMEOUT","reason":"Waiter has timed out"}`

**Comment by bnk222** [comment]
i switched to v2 but i am getting  Unable to resolve action `aws-actions/amazon-ecs-render-task-definition@v2`, unable to find version `v2`

**Comment by bnk222** [comment]
only switch this aws-actions/amazon-ecs-deploy-task-definition@v1 -> aws-actions/amazon-ecs-deploy-task-definition@v2

**Comment by paulmothapo** [comment]
If updating to v2 still causes an error, try to remove the line containing "enableFaultInjection":false in the `task-definition.json`

**Comment by fabiendeborde** [comment]
It was working fine with v2 until about an hour ago and now I am also getting an error:
`{"state":"TIMEOUT","reason":"Waiter has timed out"}`

**Comment by char-yb** [comment]
![image](https://github.com/user-attachments/assets/89b727ab-813a-4882-8e93-98a7d069da14)

Hello, Errors such as 'Unexpected key 'enableFaultInjection' found in parameters' are still occurring.
I wonder how the error has been resolved

```yml
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECR_CONTAINER_NAME }}
          image: ${{IMAGE_TAG}}
```

I'm currently using it in this yml, which looks like the top.

**Comment by paulmothapo** [comment]
@char-yb  update `aws-actions/amazon-ecs-deploy-task-definition@v1` to v2

**Comment by habdelra** [comment]
When I switched to v2 I started seeing the message: `{"state":"TIMEOUT","reason":"Waiter has timed out"}`. When I set `wait-for-service-stability` to false this message went away. Is there a change to how waiting for service stability occurs in v2?

**Comment by pas256** [comment]
@omkhegde, do you need any help fixing this?

**Comment by char-yb** [comment]
@paulmothapo
```
// TO-BE
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_CONTAINER_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
```

Upgrading to v2 fixed the issue for me.
Thank u.
