### ISSUE TITLE
Error: Run task failed: [null]

### ISSUE THREAD

**Issue by pauljricks** [aws-actions/amazon-ecs-deploy-task-definition#757]
I'm trying to deploy a new task using the below action:
```
      - name: migrate db
        uses: aws-actions/amazon-ecs-deploy-task-definition@d32c66a232260d9bb046751620411e28cc119733
        with:
          task-definition: ${{ steps.migrate-task-def.outputs.task-definition }}
          service: ${{ env.MIGRATE_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          desired-count: 1
          wait-for-service-stability: true
          run-task: true
          wait-for-task-stopped: true
          run-task-subnets: "***"
          run-task-security-groups: "***"
```

But the result is `Error: Run task failed: [null]`. I'm not really sure how to debug this and any help you can give me would be greatly appreciated.
