### ISSUE TITLE
Configuring the AppSpec.yaml during action?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [aws-actions/amazon-ecs-deploy-task-definition#76]
I'm somewhat confused as to how to update the appspec.yaml file during the GH action since the task definition is continuously updated (is there a way to stop registering tasks if nothing changes? I just switched the IMAGE_TAG of the build image portion to "latest" instead of making newer images.).

For me, when using CodeDeploy in console and manually inputting my appspec file' contents, it was always rejected for some kind of parsing error when using * or simply omitting the account ID and such.

I've resorted to a full arn with an appspec file like this:

```
version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-region:0000000:task-definition/application-stack:6"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
```
But my issue is that last portion: the ":6". Whenever I replace it with *, it doesn't work. Whenever I have an arn that omits the region name or account ID, CodeDeploy errors saying the arn can't be parsed.

`arn:aws:ecs:::task-definition/application-stack:*`

(Any of those replacements in any combination would not work).

So I wonder what the typical appspec.yaml or just a complete repo with GH action integration would look like. And do task definitions incur charges??? I'm just mighty confused as no one online answer my AWS questions.

**Comment by clareliguori** [comment]
Hi @Andrew-Chen-Wang, this action registers the new task definition and then updates the appspec for you with the new task definition ARN.  After you initially register the ECS service with CodeDeploy, you can leave a placeholder string for TaskDefinition in the appspec file in your repo like this.  There is no need to update the appspec yourself with a task definition ARN in the GitHub Actions workflow.

```
version: 1

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "Placeholder: GitHub Actions will fill this in"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
```
